### ISSUE TITLE
Send post  a person with @user link clickable

### ISSUE THREAD

**Issue by rogertelles** [bills-appworks/bsky-sh-cli#1]
Example: 

Hello @lulaoficial.bsky.social how are you? 

problem: 

Does not generate this user's @user link clickable

Sorry my poor english. 
my first language is portuguese. 

Congratz for this bash-cli bluesky.

**Comment by bills-appworks** [comment]
Thank you for contacting me. English is not my first language either :-)
As you pointed out, user links (mentions) are not currently supported.
I would like to respond in the future.

**Comment by rogertelles** [comment]
I understand that it is not yet supported at this time. I look forward to news in the future and will continue testing this wonderful application. Congratulations on the work.

i using google translator for sent message. rsrs

**Comment by bills-appworks** [comment]
I was able to implement it in my current development, so I think it will be released in the near future.
- post from bsky-sh-cli
![mention-001](https://github.com/user-attachments/assets/af1e4650-33e5-439c-9194-93e42a85dbab)
- display on official bsky.app web client
![mention-002](https://github.com/user-attachments/assets/ad688c69-5991-4788-a885-b74cf28e8b8e)

**Comment by rogertelles** [comment]
> I was able to implement it in my current development, so I think it will be released in the near future.
> 
> * post from bsky-sh-cli
>   ![mention-001](https://private-user-images.githubusercontent.com/29707864/350724750-af1e4650-33e5-439c-9194-93e42a85dbab.png?RRovnc-fCMLTysIOVkrjUmejZwUEKKpDUa2uY)
> * display on official bsky.app web client
>   ![mention-002](https://private-user-images.githubusercontent.com/29707864/350724755-ad688c69-5991-4788-a885-b74cf28e8b8e.png?

Excellent, exactly what I need.

**Comment by bills-appworks** [comment]
Please check that this has been supported in v0.8.0 release.

**Comment by rogertelles** [comment]
Testing v0.8.0 now...

**Comment by rogertelles** [comment]
My first test.. not work correct 

link: https://bsky.app/profile/roger-t.bsky.social/post/3kxsj2bu7g42h 

My command: 

bsky post --text 'Ola presidente @lulaoficial.bsky.social, boa tarde' 

@bills-appworks exist extra params ? 

I updated the version this way: 
1) I downloaded version 0.8
2) unzip 
3) I copied the 2 lib and bin directories to where the others were. 
If you need to remove everything and install again, let me know.

thanks

**Comment by rogertelles** [comment]
News work correct using text-file ;) 
command: 

bsky post --text-file text-file 
======================
--preview work correct too ;) 
======================
https://bsky.app/profile/roger-t.bsky.social/post/3kxsknmb3ra2z 

file: content
----------------
Recomendo seguir  
@lulaoficial.bsky.social
@pt-brasil.bsky.social
@pimenta13br.bsky.social 
SEGUE ESQUERDA! 🇧🇷🇷🇺🇨🇳🇮🇷🇵🇸🇮🇶🇨🇺🇿🇦
PALESTINA LIVRE 🇵🇸✊🏻 #FreePalestina
------------
I sent and this is perfect , congrats @bills-appworks 
For me this issue is closed. 
My preference is tex-file work,

**Comment by bills-appworks** [comment]
Sorry for the inconvenience.
In the case where it failed, it was due to a comma immediately following the mention.
There is no problem as long as there is a space between the mention and the comma. The same goes for the --text-file option. In a successful case, there are no characters before or after the mention string.
Even in the official app, mentions will be disabled if you enter them continuously, but if you focus on the mention string later, you can enable it as a mention, which is difficult ;-)
Thank you for making me aware of the possibility of delimiters other than whitespace.
We will consider how to respond (or not) in the future. If we do not respond, we will close this issue.

**Comment by rogertelles** [comment]
hello @bills-appworks , thanks for all feedback. 

yes, working... 

https://bsky.app/profile/roger-t.bsky.social/post/3kxtdsa22fz2w 

I understand about ',' and space. 
I agree, for close this issue. 
Thanks Again. 

ps: I studing translation for portuguese the readme.pt in future. 
I go to send email for you.  

i try send chat private with my email in https://bsky.app/profile/ax65028086.bills-appworks.net rsrs but no open. 

i sent here: roger.telles.social@gmail.com > 
thanks and sorry my bad english

**Comment by bills-appworks** [comment]
Regarding delimiters other than spaces (such as commas) in mention strings, the side effects of their implementation are uncertain, so I would like to make the current behavior the specification and close this issue.
As an example, if you misspelled `@example.com` as `@example,com` (period and comma), you intended to mention the `example.com` user, but the unintentional `example(.bsky.social)` to mention a user.

The README in Portuguese is great and welcome.
How about saving it to your Gist and sharing it?

**Comment by rogertelles** [comment]
yes, 
> "but the unintentional example(.bsky.social) to mention a user."  

i agree . 
How do I close the issue? 

> The README in Portuguese is great and welcome.
How about saving it to your Gist and sharing it?

yes, i go to send in gist. Good idea, Thanks

**Comment by rogertelles** [comment]
Starting work for translation... 

[Redme-pt](https://github.com/rogertelles/wiki-bsky-sh-cli-pt/wiki/README_PT)

**Comment by bills-appworks** [comment]
(English)
Thank you for your efforts.
Once I have included the Portuguese README and released it, I will close the issue.
(Portuguese)
Obrigado por seus esforços.
Depois de incluir o README em português e lançá-lo, encerrarei o problema.
(Japanese)
あなたの取り組みに感謝します。
ポルトガル語版READMEを取り込んでリリースしたら、issueは私がクローズします。

**Comment by rogertelles** [comment]
oops , thanks 
english
Obrigado 
portuguese
ありがとう
(japanese ? using translator)

**Comment by bills-appworks** [comment]
The mention function has been implemented in v0.8.0, and document translation will be addressed separately in #3, so this issue will be closed.
