### ISSUE TITLE
ERROR: post command failed after installation

### ISSUE THREAD

**Issue by BeDazzleMe** [bills-appworks/bsky-sh-cli#4]
Hi,

I have installed on RH, BlueSky account verified and normal web posts work fine.

When I try to post from bsky it fails with 'ERROR: post command failed'
Dependencies present.

bsky login --handle 'XXXX' --password 'YYY'
(login success)
bsky post --text 'This is a test.'
(ERROR: post command failed)

I see there is some debug capability however it's not clear how to enable for posts.

**Comment by bills-appworks** [comment]
Thank you for trying to use the tool.
Please let me check the results of executing the following command.
1. BSKYSHCLI_DEBUG=ON bsky post --text 'This is a test'
2. cat $HOME/.bsky_sh_cli/debug/core_post
3. bsky --version

**Comment by BeDazzleMe** [comment]
> Thank you for trying to use the tool. Please let me check the results of executing the following command.
> 
> 1. BSKYSHCLI_DEBUG=ON bsky post --text 'This is a test'
> 2. cat $HOME/.bsky_sh_cli/debug/core_post
> 3. bsky --version

Thank you for the reply, much appreciated.
Here are the results.

BSKYSHCLI_DEBUG=ON bsky post --text 'This is a test'
ERROR: API error: {"error":"InvalidRequest","message":"Error: uris/0 must be a valid at-uri"}

cat $HOME/.bsky_sh_cli/debug/core_post
{"error":"InvalidRequest","message":"Could not find repo: handleremoved.bsky.social"}

bsky --version
bsky (bsky-sh-cli) 0.11.0

**Comment by bills-appworks** [comment]
Let me confirm. Are you using a custom hosting provider (PDS) with Bluesky authentication?
![image](https://github.com/user-attachments/assets/59346f54-10dd-4e7a-ab32-1673549d0a71)

**Comment by BeDazzleMe** [comment]
> Let me confirm. Are you using a custom hosting provider (PDS) with Bluesky authentication? ![image](https://private-user-images.githubusercontent.com/29707864/367258002-59346f54-10dd-4e7a-ab32-1673549d0a71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMjczNTYsIm5iZiI6MTcyNjIyNzA1NiwicGF0aCI6Ii8yOTcwNzg2NC8zNjcyNTgwMDItNTkzNDZmNTQtMTBkZC00ZTdhLWFiMzItMTY3MzU0OWQwYTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDExMzA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1OTJkNWEwODE0Y2YyZTM1MjczYWI3NDk0ZGVjYTUyM2E1ZTc2ZTI0ZDBkYzEwODg5ZWI1MTViZjk4OTMxZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B9do40__8kKAw6tb8CzYCt4yG6Vmc2C_yugLGrQxRtw)

No, this is a plain CentOS host with no special configuration. No restrictions, I own the machine and infrastructure.

**Comment by bills-appworks** [comment]
I'm sorry for misleading you.
I want to investigate "how to connect to Bluesky" on the web, not your OS environment.
From the debug information, your Bluesky account seems to be special.

**Comment by BeDazzleMe** [comment]
> I'm sorry for misleading you. I want to investigate "how to connect to Bluesky" on the web, not your OS environment. From the debug information, your Bluesky account seems to be special.

It's a brand new BlueSky account, verified and is able to post from the web interface.

I just posted again and it now works. This is approximately 24 hours after I created the account.

# bsky post --text 'This is a test'
[ViewIndex:1] [langs:]
Handle Name Here  @handleremoved.bsky.social  2024-09-14 08:14:32
This is a test
Reply:0 Repost:0 Quote:0 Like:0

Perhaps BlueSky does not allow new accounts to post via API immediately after creation ?

Anyway, it is now working, thank you.

**Comment by bills-appworks** [comment]
Hmm, that's strange...
I don't know of any such restrictions, but there may be some rules.
If a similar thing happens in the future, I'd like to refer to your case.
If you don't mind, I will close this issue after a while.
I'm glad it worked. I'm glad you're using this tool. Thank you for your cooperation!

**Comment by BeDazzleMe** [comment]
> Hmm, that's strange... I don't know of any such restrictions, but there may be some rules. If a similar thing happens in the future, I'd like to refer to your case. If you don't mind, I will close this issue after a while. I'm glad it worked. I'm glad you're using this tool. Thank you for your cooperation!

No problem, just call out if you want any further information.
